### ISSUE TITLE
idk whats wrong

### ISSUE THREAD

**Issue by AshbornLV** [Marcel-TO/DL2_Save_Editor#136]
i installed all dependencies with all cmd prompts and after i tryed to launch application with cmd promt it gave out lots of errors

**To Reproduce**
![Screenshot 2024-11-19 032627](https://github.com/user-attachments/assets/ea3de49b-4261-4eca-bec4-f09188097466)

**Desktop (please complete the following information):**
 - OS: window 11
 - Browser chrome

**Additional context**

**Comment by Marcel-TO** [comment]
NPM has to be run inside the project itself where the `package.json` file is located.
As you can see in the error message, it tries to locate the this file inside the root of the repository.

if you use the `cd savegame-editor` to move the terminal inside the project, then you should be able to run it locally.

I am going to close this issue. If you find yourself still struggling to reproduce, please reopen this issue.
