### ISSUE TITLE
No inventory tab

### ISSUE THREAD

**Issue by MrSaussissonSec** [Marcel-TO/DL2_Save_Editor#137]
**Describe the bug**
Recently installed the latest version. Everything seems to be working fine, except the "Inventory" tab, which is totally empty.

**To Reproduce**
1. Go to 'Inventory' tab.

**Desktop (please complete the following information):**
 - OS: Win64
 - Version : Latest
![image](https://github.com/user-attachments/assets/793ad0a5-2e75-4456-974e-576e771795ed)

**Comment by samdgea** [comment]
yup, after upgrading the game save game version, everything broken

**Comment by Marcel-TO** [comment]
After the latest patches of the game, the savefile structure got changed. This resulted in a now wrong index calculation for the editor. With wrong index, the editor can run into issues regarding inventory items.

Please either use an older version of your save. or wait for a future release until this issue can be fixed. There have been improvements made on the dev version, but there are still more things to address before I can confidently release those changes.
